name: Update Hub Projects from projects.yml

on:
  push:
    branches:
      - main
    paths:
      - 'projects.yml' # The single trigger file
  workflow_dispatch:

jobs:
  build-project-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build projects.json from projects.yml
        id: build
        run: |
          # Create projects.json with proper array structure for the frontend
          echo "Building projects.json from projects.yml..."
          
          # Initialize the JSON array
          echo "[]" > projects.json
          
          # Process each project entry
          yq eval -o=json '.[]' projects.yml > temp_projects.json
          
          while IFS= read -r project_entry; do
            # Extract the repo URL and overrides
            repo_url=$(echo "$project_entry" | jq -r '.repo')
            overrides=$(echo "$project_entry" | jq '.overrides // {}')
            
            echo "Processing repository: $repo_url"
            repo_path=$(echo "$repo_url" | sed 's|https://github.com/||')
            meta_url="https://raw.githubusercontent.com/${repo_path}/main/project-meta.json"
            
            # Fetch the base metadata from the project repo
            echo "Fetching metadata from: $meta_url"
            base_metadata=$(curl -sfL "$meta_url" || echo '{}')
            
            if [[ "$base_metadata" == "{}" ]] || [[ -z "$base_metadata" ]]; then
              echo "WARNING: No project-meta.json found for $repo_url. Using fallback metadata."
              repo_name=$(basename "$repo_url")
              base_metadata="{\"name\":\"$repo_name\",\"description\":\"Project repository\",\"technologies\":[\"unknown\"],\"category\":\"other\",\"status\":\"active\",\"language\":\"unknown\"}"
            fi
            
            # Transform metadata to match frontend expectations and add hosted URL logic
            frontend_ready=$(echo "$base_metadata" | jq --argjson overrides "$overrides" --arg repo_url "$repo_url" '
            {
              title: (.name // "Unknown Project"),
              description: (.description // "No description available"),
              icon: (.icon // "bi-box-seam"),
              url: (if .hosted_url then .hosted_url else $repo_url end),
              status: (.status // "active"),
              tags: {
                technology: (.technologies // ["unknown"]),
                category: [(.category // "other")],
                language: [(.language // "unknown")]
              }
            } + $overrides')
            
            echo "Generated frontend data: $frontend_ready"
            
            # Add to the projects array
            jq --argjson new_project "$frontend_ready" '. += [$new_project]' projects.json > temp.json && mv temp.json projects.json
            
          done < temp_projects.json
          
          # Clean up
          rm -f temp_projects.json
          
          echo "--- Generated projects.json ---"
          cat projects.json | jq .
          echo "------------------------------"

      - name: Commit and Push if Changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet projects.json; then
            echo "Changes detected in projects.json. Committing..."
            git add projects.json
            git commit -m "Automated update of projects.json"
            git push
          else
            echo "No changes to projects.json. Nothing to commit."
          fi